version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the website..."
      - npm run build
  post_build:
    commands:
      - echo "Copying files to deployment directory..."
      - aws s3 sync build/ s3://codepipeline-ap-south-1-370153895447