name: Deploy to AWS
on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-south-1

      - name: Install and build dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name testreports --version-label ${{ github.sha }} --source-bundle S3Bucket=elasticbeanstalk-ap-south-1-529973900162,S3Key=my-app.zip
          aws elasticbeanstalk update-environment --environment-name Testreports-env --version-label ${{ github.sha }}
